[tool.poetry]
name = "contiguity-base"
version = "1.2.0"
description = ""
authors = ["Дмитрий Бондарев <skinxedovich@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
httpx = "^0.27.2"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.3"
pytest-asyncio = "^0.24.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.6.8"

[tool.ruff]
line-length = 120
exclude = [
    "migrations",
    "manage.py",
]

[tool.ruff.lint]
unfixable = ["B"]
select = [
    "F",
    "B",
    "E",
    "I",
    "UP",
    "N",
    "ANN",
    "Q"
]
ignore = ["ANN002", "ANN003", "ANN101", "ANN102", "ANN204"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
